<!DOCTYPE html>
<html class="writer-html5" lang="ja" >
<head>
  <meta charset="utf-8" /><meta name="generator" content="Docutils 0.17.1: http://docutils.sourceforge.net/" />

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>例外処理 &mdash; 仕事ですぐに使えるTypeScript  ドキュメント</title>
      <link rel="stylesheet" href="_static/pygments.css" type="text/css" />
      <link rel="stylesheet" href="_static/css/theme.css" type="text/css" />
  <!--[if lt IE 9]>
    <script src="_static/js/html5shiv.min.js"></script>
  <![endif]-->
  
        <script data-url_root="./" id="documentation_options" src="_static/documentation_options.js"></script>
        <script src="_static/jquery.js"></script>
        <script src="_static/underscore.js"></script>
        <script src="_static/_sphinx_javascript_frameworks_compat.js"></script>
        <script src="_static/doctools.js"></script>
        <script src="_static/sphinx_highlight.js"></script>
        <script src="_static/translations.js"></script>
    <script src="_static/js/theme.js"></script>
    <link rel="index" title="索引" href="genindex.html" />
    <link rel="search" title="検索" href="search.html" />
    <link rel="next" title="モジュール" href="module.html" />
    <link rel="prev" title="非同期処理" href="async.html" /> 
</head>

<body class="wy-body-for-nav"> 
  <div class="wy-grid-for-nav">
    <nav data-toggle="wy-nav-shift" class="wy-nav-side">
      <div class="wy-side-scroll">
        <div class="wy-side-nav-search" >
            <a href="index.html" class="icon icon-home"> 仕事ですぐに使えるTypeScript
          </a>
<div role="search">
  <form id="rtd-search-form" class="wy-form" action="search.html" method="get">
    <input type="text" name="q" placeholder="Search docs" />
    <input type="hidden" name="check_keywords" value="yes" />
    <input type="hidden" name="area" value="default" />
  </form>
</div>
        </div><div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="Navigation menu">
              <p class="caption" role="heading"><span class="caption-text">TypeScriptの世界を知る</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="preface.html">前書き</a></li>
<li class="toctree-l1"><a class="reference internal" href="ecosystem.html">Node.jsエコシステムを体験しよう</a></li>
</ul>
<p class="caption" role="heading"><span class="caption-text">TypeScriptの書き方</span></p>
<ul class="current">
<li class="toctree-l1"><a class="reference internal" href="variable.html">変数</a></li>
<li class="toctree-l1"><a class="reference internal" href="primitive.html">プリミティブ型</a></li>
<li class="toctree-l1"><a class="reference internal" href="complex.html">複合型</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax.html">基本的な構文</a></li>
<li class="toctree-l1"><a class="reference internal" href="typing.html">基本的な型付け</a></li>
<li class="toctree-l1"><a class="reference internal" href="function.html">関数</a></li>
<li class="toctree-l1"><a class="reference internal" href="otherbuiltinobjects.html">その他の組み込み型・関数</a></li>
<li class="toctree-l1"><a class="reference internal" href="class.html">クラス</a></li>
<li class="toctree-l1"><a class="reference internal" href="async.html">非同期処理</a></li>
<li class="toctree-l1 current"><a class="current reference internal" href="#">例外処理</a><ul>
<li class="toctree-l2"><a class="reference internal" href="#typescript">TypeScriptの例外処理構文</a></li>
<li class="toctree-l2"><a class="reference internal" href="#error"><code class="docutils literal notranslate"><span class="pre">Error</span></code> クラス</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id2">標準の例外クラス</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#id3">例外処理とコードの読みやすさ</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#try"><code class="docutils literal notranslate"><span class="pre">try</span></code> 節はなるべく狭くする</a></li>
<li class="toctree-l3"><a class="reference internal" href="#error-throw"><code class="docutils literal notranslate"><span class="pre">Error</span></code> 以外を <code class="docutils literal notranslate"><span class="pre">throw</span></code> しない</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#id4">リカバリー処理の分岐のためにユーザー定義の例外クラスを作る</a></li>
<li class="toctree-l2"><a class="reference internal" href="#id5">例外処理を使わないエラー処理</a></li>
<li class="toctree-l2"><a class="reference internal" href="#id6">非同期と例外処理</a></li>
<li class="toctree-l2"><a class="reference internal" href="#id7">例外とエラーの違い</a></li>
<li class="toctree-l2"><a class="reference internal" href="#id8">例外処理のハンドリングの漏れ</a></li>
<li class="toctree-l2"><a class="reference internal" href="#id9">例外処理機構以外で例外を扱う</a></li>
<li class="toctree-l2"><a class="reference internal" href="#id10">まとめ</a></li>
</ul>
</li>
<li class="toctree-l1"><a class="reference internal" href="module.html">モジュール</a></li>
<li class="toctree-l1"><a class="reference internal" href="console.html"><code class="docutils literal notranslate"><span class="pre">console.log</span></code>によるログ出力</a></li>
</ul>
<p class="caption" role="heading"><span class="caption-text">中級のテクニック</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="generics.html">ジェネリクス</a></li>
<li class="toctree-l1"><a class="reference internal" href="functional.html">関数型指向のプログラミング</a></li>
<li class="toctree-l1"><a class="reference internal" href="class2.html">クラス上級編</a></li>
<li class="toctree-l1"><a class="reference internal" href="reactive.html">リアクティブ</a></li>
<li class="toctree-l1"><a class="reference internal" href="advance.html">高度なテクニック</a></li>
</ul>
<p class="caption" role="heading"><span class="caption-text">環境ごとのTips（共通環境・ブラウザ以外）</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="prodenv.html">ソフトウェア開発の環境を考える</a></li>
<li class="toctree-l1"><a class="reference internal" href="baseenv.html">基本の環境構築</a></li>
<li class="toctree-l1"><a class="reference internal" href="libenv.html">ライブラリ開発のための環境設定</a></li>
<li class="toctree-l1"><a class="reference internal" href="clienv.html">CLIツール・ウェブサーバー作成のための環境設定</a></li>
<li class="toctree-l1"><a class="reference internal" href="ci.html">CI（継続的インテグレーション）環境の構築</a></li>
<li class="toctree-l1"><a class="reference internal" href="deploy.html">成果物のデプロイ</a></li>
<li class="toctree-l1"><a class="reference internal" href="version.html">使用ライブラリのバージョン管理</a></li>
</ul>
<p class="caption" role="heading"><span class="caption-text">環境ごとのTips（ブラウザ環境）</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="browserenv.html">ブラウザ環境</a></li>
<li class="toctree-l1"><a class="reference internal" href="browserobjects.html">ブラウザ関連の組み込み型</a></li>
<li class="toctree-l1"><a class="reference internal" href="react.html">Reactの環境構築</a></li>
<li class="toctree-l1"><a class="reference internal" href="vue.html">Vue.jsの環境構築</a></li>
<li class="toctree-l1"><a class="reference internal" href="webparcel.html">Parcelを使ったウェブ開発</a></li>
<li class="toctree-l1"><a class="reference internal" href="electron.html">Electronアプリケーションの作成</a></li>
</ul>
<p class="caption" role="heading"><span class="caption-text">Appendix</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="recommended.html">おすすめのパッケージ・ツール</a></li>
<li class="toctree-l1"><a class="reference internal" href="contributors.html">貢献者</a></li>
</ul>

        </div>
      </div>
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap"><nav class="wy-nav-top" aria-label="Mobile navigation menu" >
          <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
          <a href="index.html">仕事ですぐに使えるTypeScript</a>
      </nav>

      <div class="wy-nav-content">
        <div class="rst-content">
          <div role="navigation" aria-label="Page navigation">
  <ul class="wy-breadcrumbs">
      <li><a href="index.html" class="icon icon-home"></a></li>
      <li class="breadcrumb-item active">例外処理</li>
      <li class="wy-breadcrumbs-aside">
            <a href="_sources/exception.rst.txt" rel="nofollow"> View page source</a>
      </li>
  </ul>
  <hr/>
</div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
           <div itemprop="articleBody">
             
  <section id="id1">
<h1>例外処理<a class="headerlink" href="#id1" title="この見出しへのパーマリンク"></a></h1>
<p>TypeScriptはJavaと似たような例外処理機構を備えています。ただし、ベースとなっているJavaScriptの言語の制約から、使い勝手などは多少異なります。</p>
<section id="typescript">
<h2>TypeScriptの例外処理構文<a class="headerlink" href="#typescript" title="この見出しへのパーマリンク"></a></h2>
<p>A → B → Cと順番にタスクをこなすプログラムがあったとします。例えば、データを取得してきて、それを加工して、他のサーバーに送信するバッチ処理のプログラムとかを想像してください。
これが順番通りうまくいけば何も問題がありませんが、例えば、データ取得時や送信時にネットワークにうまく繋がらない、加工しようと思ったが、サーバーから送られてきたデータが想定と違ったなど、うまくいかないこともありえます。その場合に、処理を中断する（例外を投げる）、中断したことを察知して何かしらの対処をする（回復処理）を行います。これらの機構をまとめて例外処理と呼んだりします。</p>
<p><code class="docutils literal notranslate"><span class="pre">throw</span></code> を使って例外を投げます。 <code class="docutils literal notranslate"><span class="pre">throw</span></code> すると、その行でその関数やメソッド内部の処理は中断し、呼び出し元、そのさらに呼び出し元、と処理がどんどん巻き戻っていきます。最終的に回復処理を行う <code class="docutils literal notranslate"><span class="pre">try</span></code> 節/ <code class="docutils literal notranslate"><span class="pre">catch</span></code> 節のペアにあたるまで巻き戻ります。</p>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="k">throw</span><span class="w"> </span><span class="ow">new</span><span class="w"> </span><span class="ne">Error</span><span class="p">(</span><span class="s2">&quot;ネットワークアクセス失敗&quot;</span><span class="p">);</span><span class="w"></span>

<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="s2">&quot;この行は実行されない&quot;</span><span class="p">);</span><span class="w"></span>
</pre></div>
</div>
<p>例外を投げうる処理の周りは <code class="docutils literal notranslate"><span class="pre">try</span></code> 節で囲みます。 <code class="docutils literal notranslate"><span class="pre">catch</span></code> 節は例外が飛んできたときに呼ばれるコードブロックです。例外が発生してもしなくても、必ず通るのが <code class="docutils literal notranslate"><span class="pre">finally</span></code> 節です。後片付けの処理を書いたりします。
<code class="docutils literal notranslate"><span class="pre">finally</span></code> は省略できます。</p>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="kd">const</span><span class="w"> </span><span class="nx">data</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="k">await</span><span class="w"> </span><span class="nx">getData</span><span class="p">();</span><span class="w"></span>
<span class="w">  </span><span class="kd">const</span><span class="w"> </span><span class="nx">modified</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nx">modify</span><span class="p">(</span><span class="nx">data</span><span class="p">);</span><span class="w"></span>
<span class="w">  </span><span class="k">await</span><span class="w"> </span><span class="nx">sendData</span><span class="p">(</span><span class="nx">modified</span><span class="p">);</span><span class="w"></span>
<span class="p">}</span><span class="w"> </span><span class="k">catch</span><span class="w"> </span><span class="p">(</span><span class="nx">e</span><span class="p">)</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="sb">`エラー発生 </span><span class="si">${</span><span class="nx">e</span><span class="si">}</span><span class="sb">`</span><span class="p">);</span><span class="w"></span>
<span class="p">}</span><span class="w"> </span><span class="k">finally</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="c1">// 最後に必ず呼ばれる</span><span class="w"></span>
<span class="p">}</span><span class="w"></span>
</pre></div>
</div>
<p>もし、回復処理で回復し切れない場合は、再度例外を投げることもできます。</p>
<div class="literal-block-wrapper docutils container" id="id11">
<div class="code-block-caption"><span class="caption-text">例外の再送</span><a class="headerlink" href="#id11" title="このコードへのパーマリンク"></a></div>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="c1">//</span><span class="w"></span>
<span class="p">}</span><span class="w"> </span><span class="k">catch</span><span class="w"> </span><span class="p">(</span><span class="nx">e</span><span class="p">)</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="k">throw</span><span class="w"> </span><span class="nx">e</span><span class="p">;</span><span class="w"> </span><span class="c1">// 再度投げる</span><span class="w"></span>
<span class="p">}</span><span class="w"></span>
</pre></div>
</div>
</div>
<p>Javaの例外と似ていると最初に紹介しましたが、Javaと異なるのが、ベースのJavaScriptのコードは型情報をソースコード上に持っていないという点があります。
Javaの場合は、例外の <code class="docutils literal notranslate"><span class="pre">catch</span></code> 節を複数持つことができ、それぞれの節に例外のクラスの種類を書いておくと、飛んできた例外の種類に応じて適切な節が選択されます。
JavaScriptでは1つしか書くことができません。型の種類による分岐というのも、 <code class="docutils literal notranslate"><span class="pre">catch</span></code> 節の中で <code class="docutils literal notranslate"><span class="pre">if</span></code> 文を使って行う必要があります。</p>
<p>例外クラスを自分で作る必要はありますが、Javaと同じことを実現するには、以下のようなコードになります。</p>
<div class="literal-block-wrapper docutils container" id="id12">
<div class="code-block-caption"><span class="caption-text">Javaと似たような例外の分岐</span><a class="headerlink" href="#id12" title="このコードへのパーマリンク"></a></div>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="c1">// 何かしらの処理</span><span class="w"></span>
<span class="p">}</span><span class="w"> </span><span class="k">catch</span><span class="w"> </span><span class="p">(</span><span class="nx">e</span><span class="p">)</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="c1">// instanceofを使ってエラーの種類を判別していく</span><span class="w"></span>
<span class="w">  </span><span class="k">if</span><span class="w"> </span><span class="p">(</span><span class="nx">e</span><span class="w"> </span><span class="ow">instanceof</span><span class="w"> </span><span class="nx">NoNetworkError</span><span class="p">)</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">    </span><span class="c1">// NoNetworkErrorの場合</span><span class="w"></span>
<span class="w">  </span><span class="p">}</span><span class="w"> </span><span class="k">else</span><span class="w"> </span><span class="k">if</span><span class="w"> </span><span class="p">(</span><span class="nx">e</span><span class="w"> </span><span class="ow">instanceof</span><span class="w"> </span><span class="nx">NetworkAccessError</span><span class="p">)</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">    </span><span class="c1">// NetworkAccessErrorの場合</span><span class="w"></span>
<span class="w">  </span><span class="p">}</span><span class="w"> </span><span class="k">else</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">    </span><span class="c1">// その他の場合</span><span class="w"></span>
<span class="w">  </span><span class="p">}</span><span class="w"></span>
<span class="p">}</span><span class="w"></span>
</pre></div>
</div>
</div>
</section>
<section id="error">
<h2><code class="docutils literal notranslate"><span class="pre">Error</span></code> クラス<a class="headerlink" href="#error" title="この見出しへのパーマリンク"></a></h2>
<p>例外処理で「問題が発生した」ときに情報伝達に使うのが <code class="docutils literal notranslate"><span class="pre">Error</span></code> クラスです。
さきほどの構文は <code class="docutils literal notranslate"><span class="pre">new</span></code> と同時に <code class="docutils literal notranslate"><span class="pre">throw</span></code> していましたが、ふつうのオブジェクトです。</p>
<p><code class="docutils literal notranslate"><span class="pre">Error</span></code> クラスは作成時にメッセージの文字列を受け取れます。
<code class="docutils literal notranslate"><span class="pre">name</span></code> 属性にはクラス名、 <code class="docutils literal notranslate"><span class="pre">message</span></code> には作成時にコンストラクタに渡した文字列が格納されます。</p>
<p>JavaScriptの言語の標準に含まれていない、処理系独自の機能（といっても、今のところ全ブラウザで使える）のが、 <code class="docutils literal notranslate"><span class="pre">stack</span></code> プロパティに格納されるスタックトレースです。
<code class="docutils literal notranslate"><span class="pre">throw</span></code> した関数が今までどのように呼ばれてきたかの履歴です。ファイル名や行数も書かれていたりします。これがなければTypeScriptのデバッグは数万倍困難だったでしょう。</p>
<p>なお、この行数はTypeScriptをコンパイルした後のJavaScriptのファイル名と行番号だったりしますが、ソースマップというファイルをコンパイル時に出力しておき、実行時にそれがうまく読み込めると（ブラウザなら一緒にアップロード、Node.jsはnpmの <code class="docutils literal notranslate"><span class="pre">source-map-support</span></code> パッケージを利用すれば、もともとのTypeScriptのファイル名と行番号で出力されるようになります。</p>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="kd">const</span><span class="w"> </span><span class="nx">e</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="ow">new</span><span class="w"> </span><span class="ne">Error</span><span class="p">(</span><span class="s1">&#39;エラー発生&#39;</span><span class="p">);</span><span class="w"></span>
<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="sb">`name: </span><span class="si">${</span><span class="nx">e</span><span class="p">.</span><span class="nx">name</span><span class="si">}</span><span class="sb">`</span><span class="p">);</span><span class="w"></span>
<span class="c1">// name: Error</span><span class="w"></span>
<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="sb">`message: </span><span class="si">${</span><span class="nx">e</span><span class="p">.</span><span class="nx">message</span><span class="si">}</span><span class="sb">`</span><span class="p">);</span><span class="w"></span>
<span class="c1">// message: エラー発生</span><span class="w"></span>
<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="sb">`stack: </span><span class="si">${</span><span class="nx">e</span><span class="p">.</span><span class="nx">stack</span><span class="si">}</span><span class="sb">`</span><span class="p">);</span><span class="w"></span>
<span class="c1">// stack: Error: test</span><span class="w"></span>
<span class="c1">//   at new MyError (&lt;anonymous&gt;:17:23)</span><span class="w"></span>
<span class="c1">//   at &lt;anonymous&gt;:23:9</span><span class="w"></span>
</pre></div>
</div>
<section id="id2">
<h3>標準の例外クラス<a class="headerlink" href="#id2" title="この見出しへのパーマリンク"></a></h3>
<p>それ以外にも、いろいろな例外のためのクラスがあります。TypeScriptを使っているとコンパイル前に多くの問題を潰せるため、遭遇する回数はJavaScriptよりも減ります。</p>
<ul class="simple">
<li><p><code class="docutils literal notranslate"><span class="pre">EvalError</span></code></p></li>
<li><p><code class="docutils literal notranslate"><span class="pre">RangeError</span></code></p></li>
<li><p><code class="docutils literal notranslate"><span class="pre">ReferenceError</span></code></p></li>
<li><p><code class="docutils literal notranslate"><span class="pre">SyntaxError</span></code></p></li>
<li><p><code class="docutils literal notranslate"><span class="pre">TypeError</span></code></p></li>
<li><p><code class="docutils literal notranslate"><span class="pre">URIError</span></code></p></li>
</ul>
<p>例外を受け取って何もしない（俗称：例外を握りつぶす）は行儀がよくないコードとされますが、JSONパース時には文法がおかしい場合に <code class="docutils literal notranslate"><span class="pre">SyntaxError</span></code> が発生します。 <code class="docutils literal notranslate"><span class="pre">JSON.parse()</span></code> だけは拾って無効値で初期化という処理は頻繁に行うでしょう。</p>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="kd">let</span><span class="w"> </span><span class="nx">json</span><span class="o">:</span><span class="w"> </span><span class="kt">any</span><span class="p">;</span><span class="w"></span>
<span class="k">try</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="nx">json</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nb">JSON</span><span class="p">.</span><span class="nx">parse</span><span class="p">(</span><span class="nx">jsonString</span><span class="p">);</span><span class="w"></span>
<span class="p">}</span><span class="w"> </span><span class="k">catch</span><span class="w"> </span><span class="p">(</span><span class="nx">e</span><span class="p">)</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="nx">json</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="kc">null</span><span class="p">;</span><span class="w"></span>
<span class="p">}</span><span class="w"></span>
</pre></div>
</div>
<p>あとはブラウザの <code class="docutils literal notranslate"><span class="pre">fetch()</span></code> 関数でサーバー側のAPIにアクセスするときに、ネットワークエラー（corsでの権限がない場合も）は <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> が発生します。
<code class="docutils literal notranslate"><span class="pre">fetch</span></code> はJSONをパースする場合に <code class="docutils literal notranslate"><span class="pre">SyntaxError</span></code> も発生します。</p>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="kd">const</span><span class="w"> </span><span class="nx">res</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="k">await</span><span class="w"> </span><span class="nx">fetch</span><span class="p">(</span><span class="s2">&quot;/api/users&quot;</span><span class="p">);</span><span class="w"> </span><span class="c1">// ここでTypeError発生の可能性</span><span class="w"></span>
<span class="w">  </span><span class="k">if</span><span class="w"> </span><span class="p">(</span><span class="nx">res</span><span class="p">.</span><span class="nx">ok</span><span class="p">)</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">    </span><span class="kd">const</span><span class="w"> </span><span class="nx">json</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="k">await</span><span class="w"> </span><span class="nx">res</span><span class="p">.</span><span class="nx">json</span><span class="p">();</span><span class="w">         </span><span class="c1">// ここでSyntaxError発生の可能性</span><span class="w"></span>
<span class="w">  </span><span class="p">}</span><span class="w"></span>
<span class="p">}</span><span class="w"></span>
</pre></div>
</div>
<p>よくやりがちなのが、 <code class="docutils literal notranslate"><span class="pre">ok</span></code> の確認をしない（ステータスコードが200以外でJSON以外が返ってきているときに）JSONをパースしようとしてエラーになることです。
<code class="docutils literal notranslate"><span class="pre">404</span> <span class="pre">Not</span> <span class="pre">Found</span></code> のときは、ボディが <code class="docutils literal notranslate"><span class="pre">Not</span> <span class="pre">Found</span></code> というテキストになるので、未知のトークン <code class="docutils literal notranslate"><span class="pre">N</span></code> というエラーになります。あとは403 Forbiddenのときには、未知のトークン <code class="docutils literal notranslate"><span class="pre">F</span></code> のエラーが発生します。</p>
<div class="highlight-text notranslate"><div class="highlight"><pre><span></span>SyntaxError: Unexpected token N in JSON at position 0
</pre></div>
</div>
</section>
</section>
<section id="id3">
<h2>例外処理とコードの読みやすさ<a class="headerlink" href="#id3" title="この見出しへのパーマリンク"></a></h2>
<p>例外処理も、コードを読む人の理解を手助けするための、ちょっとしたコツがあります。</p>
<section id="try">
<h3><code class="docutils literal notranslate"><span class="pre">try</span></code> 節はなるべく狭くする<a class="headerlink" href="#try" title="この見出しへのパーマリンク"></a></h3>
<p>「この関数を呼ぶと、AとBの例外が飛んでくる可能性がある」というのはできあがったソースコードを見ても情報はわかりません。
次のコード例を見ても、AからEのどこでどんな例外が飛んでくるかわからないでしょう。</p>
<div class="literal-block-wrapper docutils container" id="id13">
<div class="code-block-caption"><span class="caption-text">広すぎるtryは例外の出どころをわかりにくくする</span><a class="headerlink" href="#id13" title="このコードへのパーマリンク"></a></div>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="nx">logicA</span><span class="p">();</span><span class="w"></span>
<span class="w">  </span><span class="nx">logicB</span><span class="p">();</span><span class="w"></span>
<span class="w">  </span><span class="nx">logicC</span><span class="p">();</span><span class="w"></span>
<span class="w">  </span><span class="nx">logicD</span><span class="p">();</span><span class="w"></span>
<span class="w">  </span><span class="nx">logicE</span><span class="p">();</span><span class="w"></span>
<span class="p">}</span><span class="w"> </span><span class="k">catch</span><span class="w"> </span><span class="p">(</span><span class="nx">e</span><span class="p">)</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="c1">// エラー処理</span><span class="w"></span>
<span class="p">}</span><span class="w"></span>
</pre></div>
</div>
</div>
<p>なるべく狭くすることで、どの処理がどの例外を投げるのかが明確になります。</p>
<div class="literal-block-wrapper docutils container" id="id14">
<div class="code-block-caption"><span class="caption-text">tryの範囲を狭めると、どこで何がおきるのかがわかりやすくなる</span><a class="headerlink" href="#id14" title="このコードへのパーマリンク"></a></div>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="nx">logicA</span><span class="p">();</span><span class="w"></span>
<span class="nx">logicB</span><span class="p">();</span><span class="w"></span>
<span class="k">try</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="nx">logicC</span><span class="p">();</span><span class="w"></span>
<span class="p">}</span><span class="w"> </span><span class="k">catch</span><span class="w"> </span><span class="p">(</span><span class="nx">e</span><span class="p">)</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="c1">// エラー処理</span><span class="w"></span>
<span class="p">}</span><span class="w"></span>
<span class="nx">logicD</span><span class="p">();</span><span class="w"></span>
<span class="nx">logicE</span><span class="p">();</span><span class="w"></span>
</pre></div>
</div>
</div>
<p>実際に実行時に例外が起きうる（どんなにデバッグしても例外を抑制できない）ポイントは、外部の通信とかごく一部のはずです。あまりたくさん例外処理を書く必要もないと思いますし、書く場合もどこに書いたかがわかりやすくなります。</p>
<p>広くする問題としては、原因の違う例外が混ざってしまう点もあります。例えば、JSONのパースを何箇所かで行なっていると、それぞれの箇所で <code class="docutils literal notranslate"><span class="pre">SyntaxError</span></code> が投げられる可能性が出てきます。原因が違ってリカバリー処理が別の例外が同じ <code class="docutils literal notranslate"><span class="pre">catch</span></code> 節に入ってきてしまうと、正確に例外を仕分けを行って漏れなく対応する必要が出てきます。しかし、どの例外が投げられるかを明示できる文法がなく、実装のコードを見ないとどのような例外が投げられてくるか分かりません。そのため、「間違いなく対処できているか？」を判断するコストが極めて高くなります。</p>
</section>
<section id="error-throw">
<h3><code class="docutils literal notranslate"><span class="pre">Error</span></code> 以外を <code class="docutils literal notranslate"><span class="pre">throw</span></code> しない<a class="headerlink" href="#error-throw" title="この見出しへのパーマリンク"></a></h3>
<p>前述の <code class="docutils literal notranslate"><span class="pre">catch</span></code> 文のサンプルでは、 <code class="docutils literal notranslate"><span class="pre">e</span></code> の型が <code class="docutils literal notranslate"><span class="pre">Error</span></code> という前提で書いていました。これにより、 <code class="docutils literal notranslate"><span class="pre">catch</span></code> 節の中でコード補完がきくので、開発はしやすくなります。しかし、実際には、どの型がくるかは実行時の <code class="docutils literal notranslate"><span class="pre">throw</span></code> 次第です。 <code class="docutils literal notranslate"><span class="pre">throw</span></code> には <code class="docutils literal notranslate"><span class="pre">Error</span></code> 関連のクラス以外にも、文字列とか数値とかなんでも投げることができるからです。</p>
<p>基本的には <code class="docutils literal notranslate"><span class="pre">Error</span></code> 関連のオブジェクトだけを <code class="docutils literal notranslate"><span class="pre">throw</span></code> するようにしましょう。</p>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="o">:</span><span class="w"></span>
<span class="p">}</span><span class="w"> </span><span class="k">catch</span><span class="w"> </span><span class="p">(</span><span class="nx">e</span><span class="p">)</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="c1">// e.とタイプすると、name, messageなどがサジェストされる</span><span class="w"></span>
<span class="w">  </span><span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">e</span><span class="p">.</span><span class="nx">name</span><span class="p">);</span><span class="w"></span>
<span class="p">}</span><span class="w"></span>
</pre></div>
</div>
</section>
</section>
<section id="id4">
<h2>リカバリー処理の分岐のためにユーザー定義の例外クラスを作る<a class="headerlink" href="#id4" title="この見出しへのパーマリンク"></a></h2>
<p>例外処理のためにクラスを作ってみましょう。 <code class="docutils literal notranslate"><span class="pre">Error</span></code> を継承することで、例外クラスを作ることができます。ただし、少し <code class="docutils literal notranslate"><span class="pre">Error</span></code> クラスは特殊なので、いくつかの追加処理をコンストラクタで行う必要があります。5個例外クラスを作るとして、全部のクラスで同じ処理を書くこともできます。しかし、これが10個とか20個になると大変です。1つのベースのクラスを作り、実際にコード中で扱うクラスはこれから継承して作るようにします。</p>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="c1">// 共通エラークラス</span><span class="w"></span>
<span class="kd">class</span><span class="w"> </span><span class="nx">BaseError</span><span class="w"> </span><span class="k">extends</span><span class="w"> </span><span class="ne">Error</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="kr">constructor</span><span class="p">(</span><span class="nx">e?</span><span class="o">:</span><span class="w"> </span><span class="kt">string</span><span class="p">)</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">    </span><span class="k">super</span><span class="p">(</span><span class="nx">e</span><span class="p">);</span><span class="w"></span>
<span class="w">    </span><span class="k">this</span><span class="p">.</span><span class="nx">name</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="ow">new</span><span class="p">.</span><span class="nx">target</span><span class="p">.</span><span class="nx">name</span><span class="p">;</span><span class="w"></span>
<span class="w">    </span><span class="c1">// 下記の行はTypeScriptの出力ターゲットがES2015より古い場合(ES3, ES5)のみ必要</span><span class="w"></span>
<span class="w">    </span><span class="nb">Object</span><span class="p">.</span><span class="nx">setPrototypeOf</span><span class="p">(</span><span class="k">this</span><span class="p">,</span><span class="w"> </span><span class="ow">new</span><span class="p">.</span><span class="nx">target</span><span class="p">.</span><span class="nx">prototype</span><span class="p">);</span><span class="w"></span>
<span class="w">  </span><span class="p">}</span><span class="w"></span>
<span class="p">}</span><span class="w"></span>

<span class="c1">// BaseErrorを継承して、新しいエラーを作る</span><span class="w"></span>
<span class="c1">// statusCode属性にHTTPのステータスコードが格納できるように</span><span class="w"></span>
<span class="kd">class</span><span class="w"> </span><span class="nx">NetworkAccessError</span><span class="w"> </span><span class="k">extends</span><span class="w"> </span><span class="nx">BaseError</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="kr">constructor</span><span class="p">(</span><span class="k">public</span><span class="w"> </span><span class="nx">statusCode</span><span class="o">:</span><span class="w"> </span><span class="kt">number</span><span class="p">,</span><span class="w"> </span><span class="nx">e?</span><span class="o">:</span><span class="w"> </span><span class="kt">string</span><span class="p">)</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">    </span><span class="k">super</span><span class="p">(</span><span class="nx">e</span><span class="p">);</span><span class="w"></span>
<span class="w">  </span><span class="p">}</span><span class="w"></span>
<span class="p">}</span><span class="w"></span>

<span class="c1">// 追加の属性がなければ、コンストラクタも定義不要</span><span class="w"></span>
<span class="kd">class</span><span class="w"> </span><span class="nx">NoNetworkError</span><span class="w"> </span><span class="k">extends</span><span class="w"> </span><span class="nx">BaseError</span><span class="w"> </span><span class="p">{}</span><span class="w"></span>
</pre></div>
</div>
<p>このようにクラスをいくつも作ると、例外を受け取った <code class="docutils literal notranslate"><span class="pre">catch</span></code> 節で、リカバリーの方法を「選ぶ」ことが可能になります。
投げられたクラスごとに <code class="docutils literal notranslate"><span class="pre">instanceof</span></code> と組み合わせて条件分岐に使えます。また、この <code class="docutils literal notranslate"><span class="pre">instanceof</span></code> は型ガードになっていますので、各ブロックの中でコード補完も正しく行われます。
上記のクラスの <code class="docutils literal notranslate"><span class="pre">statusCode</span></code> も正しく補完されます。</p>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="k">await</span><span class="w"> </span><span class="nx">getUser</span><span class="p">();</span><span class="w"></span>
<span class="p">}</span><span class="w"> </span><span class="k">catch</span><span class="w"> </span><span class="p">(</span><span class="nx">e</span><span class="p">)</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="k">if</span><span class="w"> </span><span class="p">(</span><span class="nx">e</span><span class="w"> </span><span class="ow">instanceof</span><span class="w"> </span><span class="nx">NoNetworkError</span><span class="p">)</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">    </span><span class="nx">alert</span><span class="p">(</span><span class="s2">&quot;ネットワークがありません&quot;</span><span class="p">);</span><span class="w"></span>
<span class="w">  </span><span class="p">}</span><span class="w"> </span><span class="k">else</span><span class="w"> </span><span class="k">if</span><span class="w"> </span><span class="p">(</span><span class="nx">e</span><span class="w"> </span><span class="ow">instanceof</span><span class="w"> </span><span class="nx">NetworkAccessError</span><span class="p">)</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">    </span><span class="c1">// この節では、eはNetworkAccessErrorのインスタンスなので、</span><span class="w"></span>
<span class="w">    </span><span class="c1">// ↓のe.をタイプすると、statusCodeがサジェストされる</span><span class="w"></span>
<span class="w">    </span><span class="k">if</span><span class="w"> </span><span class="p">(</span><span class="nx">e</span><span class="p">.</span><span class="nx">statusCode</span><span class="w"> </span><span class="o">&lt;</span><span class="w"> </span><span class="mf">500</span><span class="p">)</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">      </span><span class="nx">alert</span><span class="p">(</span><span class="s2">&quot;プログラムにバグがあります&quot;</span><span class="p">);</span><span class="w"></span>
<span class="w">    </span><span class="p">}</span><span class="w"> </span><span class="k">else</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">      </span><span class="nx">alert</span><span class="p">(</span><span class="s2">&quot;サーバーエラー&quot;</span><span class="p">);</span><span class="w"></span>
<span class="w">    </span><span class="p">}</span><span class="w"></span>
<span class="w">  </span><span class="p">}</span><span class="w"></span>
<span class="p">}</span><span class="w"></span>
</pre></div>
</div>
<p>なお、TypeScriptは、昔のJavaのように継承を前提とした処理を書くことはほとんどありませんので、コードの中で継承を使うことも極めてまれです。Javaの場合は、 <code class="docutils literal notranslate"><span class="pre">IOException</span></code> クラスを継承したクラスがあって、入出力系のエラーなど継承階層を前提としたコードが書かれたりもしました。しかし、これは「AはBの子クラスである」という知識を持っていないと読めないコードになってしまうため、プロジェクトに入ってきたばかりの人には混乱を与えがちです。例外クラスを作る場合も、 <code class="docutils literal notranslate"><span class="pre">BaseClass</span></code> からの直系の子供クラスだけで作れば問題ありません。立派な継承ツリーの設計は不要です。あまり例外クラスが多くても使い分けに迷ったりします。</p>
<div class="admonition note">
<p class="admonition-title">注釈</p>
<p>ターゲットがES3/ES5のときに <code class="docutils literal notranslate"><span class="pre">Object.setPrototypeOf(this,</span> <span class="pre">new.target.prototype);</span></code> の行を書き忘れると、 <code class="docutils literal notranslate"><span class="pre">instanceof</span></code> が <code class="docutils literal notranslate"><span class="pre">false</span></code> を返してくるようになります。</p>
</div>
</section>
<section id="id5">
<h2>例外処理を使わないエラー処理<a class="headerlink" href="#id5" title="この見出しへのパーマリンク"></a></h2>
<p>正常に実行できなかったからといって、なんでも例外として処理しなければならないわけではありません。
例えば、ブラウザ標準の <code class="docutils literal notranslate"><span class="pre">fetch</span></code> APIの場合、通信ができたが、正常に終わらなかった場合は <code class="docutils literal notranslate"><span class="pre">ok</span></code> 属性を使って判断できます。
例外には深い階層から一発で離脱できる（途中の関数では、エラーがあったかどうかを判定不要）メリットがあります。
しかし、階層が深くなく、呼び出し元と例外処理を行うコードがすごく近い場合には、この <code class="docutils literal notranslate"><span class="pre">ok</span></code> のような属性を用意する方が管理もしやすいでしょう。</p>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="kd">const</span><span class="w"> </span><span class="nx">res</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="k">await</span><span class="w"> </span><span class="nx">fetch</span><span class="p">(</span><span class="s2">&quot;/users&quot;</span><span class="p">);</span><span class="w"></span>
<span class="k">if</span><span class="w"> </span><span class="p">(</span><span class="nx">res</span><span class="p">.</span><span class="nx">ok</span><span class="p">)</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="c1">// ステータスコードが200/300番台</span><span class="w"></span>
<span class="p">}</span><span class="w"> </span><span class="k">else</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="c1">// 400番以降</span><span class="w"></span>
<span class="p">}</span><span class="w"></span>
</pre></div>
</div>
</section>
<section id="id6">
<h2>非同期と例外処理<a class="headerlink" href="#id6" title="この見出しへのパーマリンク"></a></h2>
<p>非同期処理で難しいのがエラー処理でした。
<code class="docutils literal notranslate"><span class="pre">async</span></code> と <code class="docutils literal notranslate"><span class="pre">await</span></code> のおかげで例外処理もだいぶ書きやすくなりました。</p>
<p><code class="docutils literal notranslate"><span class="pre">Promise</span></code> では <code class="docutils literal notranslate"><span class="pre">then()</span></code> の2つめのコールバック関数でエラー処理が書けるようになりました。
また、エラー処理の節だけを書く <code class="docutils literal notranslate"><span class="pre">catch()</span></code> 節もあります。
複数の <code class="docutils literal notranslate"><span class="pre">then()</span></code> 節が連なっていても、1箇所だけエラー処理を書けば大丈夫です。
なお、一箇所もエラー処理を書かずにいて、エラーが発生すると <code class="docutils literal notranslate"><span class="pre">unhandledRejection</span></code> というエラーがNode.jsのコンソールに表示されることになります。</p>
<div class="literal-block-wrapper docutils container" id="id15">
<div class="code-block-caption"><span class="caption-text">Promiseのエラー書き方</span><a class="headerlink" href="#id15" title="このコードへのパーマリンク"></a></div>
<div class="highlight-js notranslate"><div class="highlight"><pre><span></span><span class="nx">fetch</span><span class="p">(</span><span class="nx">url</span><span class="p">).</span><span class="nx">then</span><span class="p">(</span><span class="nx">resp</span><span class="w"> </span><span class="p">=&gt;</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="k">return</span><span class="w"> </span><span class="nx">resp</span><span class="p">.</span><span class="nx">json</span><span class="p">();</span><span class="w"></span>
<span class="p">}).</span><span class="nx">then</span><span class="p">(</span><span class="nx">json</span><span class="w"> </span><span class="p">=&gt;</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">json</span><span class="p">);</span><span class="w"></span>
<span class="p">}).</span><span class="k">catch</span><span class="p">(</span><span class="nx">e</span><span class="w"> </span><span class="p">=&gt;</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="s2">&quot;エラー発生!&quot;</span><span class="p">);</span><span class="w"></span>
<span class="w">  </span><span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">e</span><span class="p">);</span><span class="w"></span>
<span class="p">});</span><span class="w"></span>
</pre></div>
</div>
</div>
<p><code class="docutils literal notranslate"><span class="pre">async</span></code> 関数の場合はもっとシンプルで、何かしらの非同期処理を実行する場合、 <code class="docutils literal notranslate"><span class="pre">await</span></code> していれば、通常の <code class="docutils literal notranslate"><span class="pre">try</span></code> 文でエラーを捕まえることができます。</p>
<div class="literal-block-wrapper docutils container" id="id16">
<div class="code-block-caption"><span class="caption-text">async関数内部のエラー処理の書き方</span><a class="headerlink" href="#id16" title="このコードへのパーマリンク"></a></div>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="kd">const</span><span class="w"> </span><span class="nx">resp</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="k">await</span><span class="w"> </span><span class="nx">fetch</span><span class="p">(</span><span class="nx">url</span><span class="p">);</span><span class="w"></span>
<span class="w">  </span><span class="kd">const</span><span class="w"> </span><span class="nx">json</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="k">await</span><span class="w"> </span><span class="nx">resp</span><span class="p">.</span><span class="nx">json</span><span class="p">();</span><span class="w"></span>
<span class="w">  </span><span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">json</span><span class="p">);</span><span class="w"></span>
<span class="p">}</span><span class="w"> </span><span class="k">catch</span><span class="w"> </span><span class="p">(</span><span class="nx">e</span><span class="p">)</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="s2">&quot;エラー発生!&quot;</span><span class="p">);</span><span class="w"></span>
<span class="w">  </span><span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">e</span><span class="p">);</span><span class="w"></span>
<span class="p">}</span><span class="w"></span>
</pre></div>
</div>
</div>
<p>エラーを発生させるには、 <code class="docutils literal notranslate"><span class="pre">Promise</span></code> 作成時のコールバック関数の2つめの引数の <code class="docutils literal notranslate"><span class="pre">reject()</span></code> コールバック関数に <code class="docutils literal notranslate"><span class="pre">Error</span></code> オブジェクトを渡しても良いですし、
<code class="docutils literal notranslate"><span class="pre">then()</span></code> 節の中で例外をスローしても発生させることができます。</p>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="k">async</span><span class="w"> </span><span class="kd">function</span><span class="w"> </span><span class="nx">heavyTask</span><span class="p">()</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="k">return</span><span class="w"> </span><span class="ow">new</span><span class="w"> </span><span class="nb">Promise</span><span class="o">&lt;</span><span class="kt">number</span><span class="o">&gt;</span><span class="p">((</span><span class="nx">resolve</span><span class="p">,</span><span class="w"> </span><span class="nx">reject</span><span class="p">)</span><span class="w"> </span><span class="p">=&gt;</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">    </span><span class="c1">// 何かしらの処理</span><span class="w"></span>
<span class="w">    </span><span class="nx">reject</span><span class="p">(</span><span class="nx">error</span><span class="p">);</span><span class="w"></span>
<span class="w">    </span><span class="c1">// こちらでもPromiseのエラーを発生可能</span><span class="w"></span>
<span class="w">    </span><span class="k">throw</span><span class="w"> </span><span class="ow">new</span><span class="w"> </span><span class="ne">Error</span><span class="p">();</span><span class="w"></span>
<span class="w">  </span><span class="p">});</span><span class="w"></span>
<span class="p">};</span><span class="w"></span>
</pre></div>
</div>
<p><code class="docutils literal notranslate"><span class="pre">Promise</span></code> 以前は非同期処理の場合は、コールバック関数の先頭の引数がエラー、という暗黙のルールで実装されていました。
ただし、1つのコールバックでも <code class="docutils literal notranslate"><span class="pre">return</span></code> を忘れると動作しませんし、通常の例外が発生して <code class="docutils literal notranslate"><span class="pre">return</span></code> されなかったりすると、コールバックの伝搬が中断されてしまいます。</p>
<div class="literal-block-wrapper docutils container" id="id17">
<div class="code-block-caption"><span class="caption-text">原始時代の非同期のエラー処理の書き方</span><a class="headerlink" href="#id17" title="このコードへのパーマリンク"></a></div>
<div class="highlight-js notranslate"><div class="highlight"><pre><span></span><span class="c1">// 旧: Promise以前</span><span class="w"></span>
<span class="nx">func1</span><span class="p">(</span><span class="nx">引数</span><span class="p">,</span><span class="w"> </span><span class="kd">function</span><span class="p">(</span><span class="nx">err</span><span class="p">,</span><span class="w"> </span><span class="nx">value</span><span class="p">)</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="k">if</span><span class="w"> </span><span class="p">(</span><span class="nx">err</span><span class="p">)</span><span class="w"> </span><span class="k">return</span><span class="w"> </span><span class="nx">err</span><span class="p">;</span><span class="w"></span>
<span class="w">  </span><span class="nx">func2</span><span class="p">(</span><span class="nx">引数</span><span class="p">,</span><span class="w"> </span><span class="kd">function</span><span class="p">(</span><span class="nx">err</span><span class="p">,</span><span class="w"> </span><span class="nx">value</span><span class="p">)</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">    </span><span class="k">if</span><span class="w"> </span><span class="p">(</span><span class="nx">err</span><span class="p">)</span><span class="w"> </span><span class="k">return</span><span class="w"> </span><span class="nx">err</span><span class="p">;</span><span class="w"></span>
<span class="w">    </span><span class="nx">func3</span><span class="p">(</span><span class="nx">引数</span><span class="p">,</span><span class="w"> </span><span class="kd">function</span><span class="p">(</span><span class="nx">err</span><span class="p">,</span><span class="w"> </span><span class="nx">value</span><span class="p">)</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">      </span><span class="c1">// 最後に実行されるコードブロック</span><span class="w"></span>
<span class="w">    </span><span class="p">});</span><span class="w"></span>
<span class="w">  </span><span class="p">});</span><span class="w"></span>
<span class="p">});</span><span class="w"></span>
</pre></div>
</div>
</div>
</section>
<section id="id7">
<h2>例外とエラーの違い<a class="headerlink" href="#id7" title="この見出しへのパーマリンク"></a></h2>
<p>この手の話になると、エラーと例外の違いとか、こっちはハンドリングするもの、こっちはOSにそのまま流すものとかいろんな議論が出てきます。例外とエラーの違いについても、コンセンサスは取れておらず、人によって意味が違ったりします。一例としては、回復可能なものがエラーで、そうじゃないものが例外といったことが言われたりします。このエントリーではエラーも例外も差をつけずに、全部例外とひっくるめて説明します。</p>
<p>例外というのはすべて、何かしらのリカバリーを考える必要があります。</p>
<ul>
<li><p>ちょっとしたネットワークのエラーなので、3回ぐらいはリトライしてみる</p>
<blockquote>
<div><ul class="simple">
<li><p>原因: ネットワークエラー</p></li>
<li><p>リカバリー: リトライ</p></li>
</ul>
</div></blockquote>
</li>
<li><p>サーバーにリクエストを送ってみたら400エラーが返ってきた</p>
<blockquote>
<div><ul class="simple">
<li><p>原因: リクエストが不正</p></li>
<li><p>リカバリー(開発時): 本来のクライアントのロジックであればバリデーションで弾いていないといけないのでこれは潰さないといけない実装バグ。とりあえずスタックトレースとかありったけの情報をconsole.logに出しておく。</p></li>
<li><p>リカバリー(本番): ありえないバグが出た、とりあえず中途半端に継続するのではなくて、システムエラー、開発者に連絡してくれ、というメッセージをユーザーに出す（人力リカバリー）</p></li>
</ul>
</div></blockquote>
</li>
<li><p>JSONをパースしたら <code class="docutils literal notranslate"><span class="pre">SyntaxError</span></code></p>
<blockquote>
<div><ul class="simple">
<li><p>原因: ユーザーの入力が不正</p></li>
<li><p>リカバリー: フォームにエラーメッセージを出す</p></li>
</ul>
</div></blockquote>
</li>
</ul>
<p>最終的には、実装ミスなのか、ユーザーが間違ってデータ入力したという実行時の値の不正なのか、ネットワークの接続がおかしい、クラウドサービスの秘密鍵が合わないみたいな環境の問題なのか、どれであったとしても、システムが自力でリカバリーする、ユーザーに通知して入力修正やWiFiのある環境で再実行などの人力リカバリーしてもらう、開発者に通知してプログラム修正するといった人力リカバリーなど、何かしらのリカバリーは絶対必要になります。</p>
<p>Node.jsで <code class="docutils literal notranslate"><span class="pre">async</span></code> / <code class="docutils literal notranslate"><span class="pre">await</span></code> やら <code class="docutils literal notranslate"><span class="pre">Promise</span></code> を一切使っていないコードの場合、エラーを無視すると、Node.js自体が最後に <code class="docutils literal notranslate"><span class="pre">catch</span></code> して、エラー詳細を表示してプログラムが終了します。これはある意味プログラムとしては作戦放棄ではありますが、「プログラムの進行が不可能なので、OSに処理を返す」というリカバリーと言えなくもないでしょう。開発者にスタックトレースを表示して後を託す、というのも立派なリカバリーの戦術の1つです。</p>
<p>ブラウザの場合、誰もキャッチしないと、開発者ツールのコンソールに表示されますが、開発者ツールを開いていない限りエラーを見ることはできません。普段から開発者コンソールを開いている人はまれだと思いますし、大部分のユーザーには正常に正常に処理が進んだのか、そうでなかったのかわかりませんので、かならずキャッチして画面に表示してあげる必要があるでしょう。</p>
<p>どちらにしても何かしらのリカバリー処理が必要となりますので、本書ではエラーと例外の区別といったことはしません。</p>
</section>
<section id="id8">
<h2>例外処理のハンドリングの漏れ<a class="headerlink" href="#id8" title="この見出しへのパーマリンク"></a></h2>
<p>例外処理が漏れた場合、ロジックが中断します。例えば、サーバー通信結果のJSONのパースでエラーが発生すると、<code class="docutils literal notranslate"><span class="pre">SyntaxError</span></code>が発生し、その後の処理が行われなくなります。そのJSONをパースして画面に表示しようとしていた場合は、通信は行われるものの、画面表示が更新されずに何も発生していないように見えます。この場合、開発者ツールをみると、<code class="docutils literal notranslate"><span class="pre">Uncaught</span> <span class="pre">Error</span></code>が記録されています。なお、将来のNode.jsではエラーコード0以外で、プログラムが終了することになっています。</p>
<figure class="align-default" id="id18">
<img alt="_images/unhandleexception.png" src="_images/unhandleexception.png" />
<figcaption>
<p><span class="caption-text">キャッチしていない例外</span><a class="headerlink" href="#id18" title="この画像へのパーマリンク"></a></p>
</figcaption>
</figure>
<p>一方、やっかいなのが、サーバー通信のエラーです。XMLHttpRequestの場合は<code class="docutils literal notranslate"><span class="pre">onerror()</span></code>コールバックでエラーを取得してハンドルする必要がありますが、うまくハンドルしてもコンソールにはエラーが残ります。fetchの場合は<code class="docutils literal notranslate"><span class="pre">Uncaught</span> <span class="pre">(in</span> <span class="pre">promise)</span> <span class="pre">Error</span></code>が出ますが、これを適切に処理しても、やはり同様のエラーが出力されます。</p>
<p>これは<a class="reference internal" href="console.html"><span class="doc">console.logによるログ出力</span></a>の章で紹介した<code class="docutils literal notranslate"><span class="pre">console.error()</span></code>出力と同じです。うまくハンドリングしても、キャッチしなかったときと同じように赤くエラーが表示されます。XHRを直接使う場合は<code class="docutils literal notranslate"><span class="pre">onerror</span></code>が設定されていなくて例外が握り潰されている可能性もゼロではないため注意しなければなりませんが、XHRをラップした<a class="reference external" href="https://www.npmjs.com/package/axios">axios</a>や、<code class="docutils literal notranslate"><span class="pre">fetch()</span></code>を使った場合には<code class="docutils literal notranslate"><span class="pre">Uncaught</span> <span class="pre">Error</span></code>の文字がなければ実装上は気にする必要はありません。</p>
<figure class="align-default" id="id19">
<img alt="_images/consoleerror.png" src="_images/consoleerror.png" />
<figcaption>
<p><span class="caption-text">うまく処理できていた場合にも同様に表示されるエラー</span><a class="headerlink" href="#id19" title="この画像へのパーマリンク"></a></p>
</figcaption>
</figure>
</section>
<section id="id9">
<h2>例外処理機構以外で例外を扱う<a class="headerlink" href="#id9" title="この見出しへのパーマリンク"></a></h2>
<p>これまでTypeScriptにおける例外処理の方法や作法などを説明してきました。しかし、ベースとなっているJavaScriptの制約により、お世辞にも使いやすい機能とは言えません。理由は以下の3つです。</p>
<ul class="simple">
<li><p>Javaの <code class="docutils literal notranslate"><span class="pre">throws</span></code> のように、メソッドがなげうる例外の種類がわからず、ソースの関数の実態やドキュメント（整備されていれば）を確認する必要がある</p></li>
<li><p>JavaやC++のように、 <code class="docutils literal notranslate"><span class="pre">catch</span></code> 節を複数書いて、型ごとの後処理を書くことができず、 <code class="docutils literal notranslate"><span class="pre">instanceof</span></code> を駆使してエラーの種類を見分けるコードを書く必要がある</p></li>
<li><p><code class="docutils literal notranslate"><span class="pre">Promise</span></code> や　<code class="docutils literal notranslate"><span class="pre">async</span></code> 関数で、何が <code class="docutils literal notranslate"><span class="pre">reject</span></code> に渡されたり、どんな例外を投げるのかを型定義に書く方法がない</p></li>
</ul>
<p>例外に関しては、補完も効かないし、型のチェックも行えません。いっそのこと、例外処理機構を忘れてしまうのも手です。例外処理のないGoでは、関数の返り値の最後がエラーという規約でコードを書きます。
TypeScriptでも、いくつか方法が考えられます。</p>
<ul class="simple">
<li><p>タプルを使ってエラーを返す（Go式）</p></li>
<li><p>オブジェクトを使ってエラーを返す</p></li>
<li><p>合併型を使ってエラーを返す</p></li>
</ul>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="kr">type</span><span class="w"> </span><span class="nx">User</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="nx">name</span><span class="o">:</span><span class="w"> </span><span class="kt">string</span><span class="p">;</span><span class="w"></span>
<span class="w">  </span><span class="nx">age</span><span class="o">:</span><span class="w">  </span><span class="kt">number</span><span class="p">;</span><span class="w"></span>
<span class="p">}</span><span class="w"></span>

<span class="c1">// タプル</span><span class="w"></span>
<span class="kd">function</span><span class="w"> </span><span class="nx">create</span><span class="p">(</span><span class="nx">name</span><span class="o">:</span><span class="w"> </span><span class="kt">string</span><span class="p">,</span><span class="w"> </span><span class="nx">age</span><span class="o">:</span><span class="w"> </span><span class="kt">number</span><span class="p">)</span><span class="o">:</span><span class="w"> </span><span class="p">[</span><span class="nx">User</span><span class="o">?</span><span class="p">,</span><span class="w"> </span><span class="ne">Error</span><span class="o">?</span><span class="p">]</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="k">if</span><span class="w"> </span><span class="p">(</span><span class="nx">age</span><span class="w"> </span><span class="o">&lt;</span><span class="w"> </span><span class="mf">0</span><span class="p">)</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">    </span><span class="k">return</span><span class="w"> </span><span class="p">[</span><span class="kc">undefined</span><span class="p">,</span><span class="w"> </span><span class="ow">new</span><span class="w"> </span><span class="ne">Error</span><span class="p">(</span><span class="s2">&quot;before born&quot;</span><span class="p">)]</span><span class="w"></span>
<span class="w">  </span><span class="p">}</span><span class="w"></span>
<span class="w">  </span><span class="k">return</span><span class="w"> </span><span class="p">[{</span><span class="nx">name</span><span class="p">,</span><span class="w"> </span><span class="nx">age</span><span class="p">}];</span><span class="w"></span>
<span class="p">}</span><span class="w"></span>

<span class="c1">// オブジェクト</span><span class="w"></span>
<span class="kd">function</span><span class="w"> </span><span class="nx">create2</span><span class="p">(</span><span class="nx">name</span><span class="o">:</span><span class="w"> </span><span class="kt">string</span><span class="p">,</span><span class="w"> </span><span class="nx">age</span><span class="o">:</span><span class="w"> </span><span class="kt">number</span><span class="p">)</span><span class="o">:</span><span class="w"> </span><span class="p">{</span><span class="nx">user?</span><span class="o">:</span><span class="w"> </span><span class="kt">User</span><span class="p">,</span><span class="w"> </span><span class="nx">error?</span><span class="o">:</span><span class="w"> </span><span class="kt">Error</span><span class="p">}</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="k">if</span><span class="w"> </span><span class="p">(</span><span class="nx">age</span><span class="w"> </span><span class="o">&lt;</span><span class="w"> </span><span class="mf">0</span><span class="p">)</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">    </span><span class="k">return</span><span class="w"> </span><span class="p">{</span><span class="nx">error</span><span class="o">:</span><span class="w"> </span><span class="kt">new</span><span class="w"> </span><span class="ne">Error</span><span class="p">(</span><span class="s2">&quot;before born&quot;</span><span class="p">)}</span><span class="w"></span>
<span class="w">  </span><span class="p">}</span><span class="w"></span>
<span class="w">  </span><span class="k">return</span><span class="w"> </span><span class="p">{</span><span class="nx">user</span><span class="o">:</span><span class="w"> </span><span class="p">{</span><span class="nx">name</span><span class="p">,</span><span class="w"> </span><span class="nx">age</span><span class="p">}};</span><span class="w"></span>
<span class="p">}</span><span class="w"></span>

<span class="c1">// 合併型</span><span class="w"></span>
<span class="kd">function</span><span class="w"> </span><span class="nx">create3</span><span class="p">(</span><span class="nx">name</span><span class="o">:</span><span class="w"> </span><span class="kt">string</span><span class="p">,</span><span class="w"> </span><span class="nx">age</span><span class="o">:</span><span class="w"> </span><span class="kt">number</span><span class="p">)</span><span class="o">:</span><span class="w"> </span><span class="nx">User</span><span class="w"> </span><span class="o">|</span><span class="w"> </span><span class="ne">Error</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">  </span><span class="k">if</span><span class="w"> </span><span class="p">(</span><span class="nx">age</span><span class="w"> </span><span class="o">&lt;</span><span class="w"> </span><span class="mf">0</span><span class="p">)</span><span class="w"> </span><span class="p">{</span><span class="w"></span>
<span class="w">    </span><span class="k">return</span><span class="w"> </span><span class="ow">new</span><span class="w"> </span><span class="ne">Error</span><span class="p">(</span><span class="s2">&quot;before born&quot;</span><span class="p">);</span><span class="w"></span>
<span class="w">  </span><span class="p">}</span><span class="w"></span>
<span class="w">  </span><span class="k">return</span><span class="w"> </span><span class="p">{</span><span class="nx">name</span><span class="p">,</span><span class="w"> </span><span class="nx">age</span><span class="p">};</span><span class="w"></span>
<span class="p">}</span><span class="w"></span>
</pre></div>
</div>
<p>この中でどれが良いかは好みの問題ですが、個人的なおすすめはオブジェクトです。タプルよりかは返り値の意味に名前をつけられるのと、合併と異なり、オプショナルチェイニングを使ってエラーチェックを簡単に書ける可能性があります。<code class="docutils literal notranslate"><span class="pre">instanceof</span></code>と毎回タイプする必要性もありません。ただ、どの書き方もマジョリティではなく、好みの問題ではあります。</p>
</section>
<section id="id10">
<h2>まとめ<a class="headerlink" href="#id10" title="この見出しへのパーマリンク"></a></h2>
<p>例外についての文法の説明、組み込みのエラー型、エラー型を自作する方法、非同期処理の例外処理などを説明してきました。
例外の設計も、一種のアーキテクチャ設計であるため、ちょっとした経験が必要になるかもしれません。</p>
<p>TypeScript、特にフロントエンドの場合、例外を無視することはユーザーの使い勝手を悪くします。どのようなことが発生し、どのケースではどのようにリカバリーするか、というのをあらかじめ決めておくと実装は楽になるでしょう。</p>
</section>
</section>


           </div>
          </div>
          <footer><div class="rst-footer-buttons" role="navigation" aria-label="Footer">
        <a href="async.html" class="btn btn-neutral float-left" title="非同期処理" accesskey="p" rel="prev"><span class="fa fa-arrow-circle-left" aria-hidden="true"></span> Previous</a>
        <a href="module.html" class="btn btn-neutral float-right" title="モジュール" accesskey="n" rel="next">Next <span class="fa fa-arrow-circle-right" aria-hidden="true"></span></a>
    </div>

  <hr/>

  <div role="contentinfo">
    <p>&#169; Copyright 2019-2020, Future Corporation.</p>
  </div>

  Built with <a href="https://www.sphinx-doc.org/">Sphinx</a> using a
    <a href="https://github.com/readthedocs/sphinx_rtd_theme">theme</a>
    provided by <a href="https://readthedocs.org">Read the Docs</a>.
   

</footer>
        </div>
      </div>
    </section>
  </div>
  <script>
      jQuery(function () {
          SphinxRtdTheme.Navigation.enable(true);
      });
  </script> 

</body>
</html>